### ISSUE TITLE
HttpProcessingError not found

### ISSUE THREAD

**Issue by slashtea** [itielshwartz/asyncio-hn#3]
HttpProcessingError method seems to be in http_exceptions.py

add `from aiohttp.http_exceptions import HttpProcessingError` to hn.py instead of `from aiohttp import HttpProcessingError`

**Comment by itielshwartz** [comment]
Hi @slashtea thanks for the comment - will try and fix in the next couple of days, also feel free to open a PR :)

**Comment by itielshwartz** [comment]
d9c29036de29b1563efa8ca9ce75992393b236ad - look like aiohttp broke backward compatiblity.
I fix the bug and also freeze the version, thanks @slashtea
